version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    ports:
      - 9200:9200
      - 9300:9300
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "http.port=9200"
      - "http.cors.allow-origin=http://elasticsearch-ui:1358,http://localhost:9004,http://127.0.0.1:9004"
      - "http.cors.enabled=true"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "http.cors.allow-credentials=true"
    volumes:
      - elasticsearch-volume:/usr/share/elasticsearch/data
    networks:
      - elk-stack

  elasticsearch-ui:
    image: appbaseio/dejavu:latest
    ports:
      - 9004:1358
    networks:
      - elk-stack
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    ports:
      - 5601:5601
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elk-stack
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:7.16.2
    container_name: logstash
    networks:
      - elk-stack

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.16.2
    container_name: metricbeat
    networks:
      - elk-stack

  apm_server:
    image: docker.elastic.co/apm/apm-server:7.16.2
    container_name: apm_server
    ports:
      - 8200:8200
    networks:
      - elk-stack

volumes:
  elasticsearch-volume:
  kibana-volume:

networks:
  elk-stack:
