version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    ports:
      - 9200:9200
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - elasticsearch-volume:/usr/share/elasticsearch/data
    networks:
      - elk-stack

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    ports:
      - 5601:5601
    container_name: kibana
    networks:
      - elk-stack

  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.1
    container_name: logstash
    networks:
      - elk-stack

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.6.1
    container_name: metricbeat
    networks:
      - elk-stack

  apm_server:
    image: docker.elastic.co/apm/apm-server:7.6.1
    container_name: apm_server
    ports:
      - 8200:8200
    networks:
      - elk-stack

volumes:
  elasticsearch-volume:
  kibana-volume:

networks:
  elk-stack:
