version: "3.7"

services:
  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_volume:/data
    networks:
      - portainer_network

volumes:
  portainer_volume:

networks:
  portainer_network:
